require("eason.plugins-setup")
require("eason.core.keymaps")
require("eason.core.options")
require("eason.core.colorscheme")
require("eason.plugins.nvim-tree")
require("eason.plugins.lualine")
require("eason.plugins.autopairs")
require("eason.plugins.treesitter")
require("eason.plugins.gitsigns")
require("eason.plugins.lspconfig")
require("eason.plugins.completion")
require("eason.plugins.telescope")

vim.api.nvim_set_hl(0, "Cursor", {fg='grey7', bg='MediumSpringGreen'})
vim.opt.guicursor = 'a:block-Cursor,a:blinkon100'
